// This file is auto-generated by @hey-api/openapi-ts

export type DashboardViewModel = {
    id: number;
    name: string;
    url: string;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ExportWebsiteData = {
    body?: {
        SiteUrl?: string;
        AdditionalUrls?: Array<string>;
        TargetUrl?: string;
        OutputFolder?: string;
    };
    path?: never;
    query?: never;
    url: '/umbraco/umbracocommunityhtmlexporter/api/v1/export-website';
};

export type ExportWebsiteErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ExportWebsiteResponses = {
    /**
     * OK
     */
    200: string;
};

export type ExportWebsiteResponse = ExportWebsiteResponses[keyof ExportWebsiteResponses];

export type GetDomainsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracocommunityhtmlexporter/api/v1/get-domains';
};

export type GetDomainsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetDomainsResponses = {
    /**
     * OK
     */
    200: Array<DashboardViewModel>;
};

export type GetDomainsResponse = GetDomainsResponses[keyof GetDomainsResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44396' | (string & {});
};
