// This file is auto-generated by @hey-api/openapi-ts

export type DashboardDomains = {
    id: number;
    name: string;
    url: string;
};

export type DashboardViewModel = {
    domains: Array<DashboardDomains>;
    settings: ExportHtmlSettings;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type ExportHtmlSettings = {
    targetUrl: string;
    outputFolder: string;
    additionalUrls: Array<string>;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ExportWebsiteData = {
    body?: {
        SiteUrl?: string;
        AdditionalUrls?: Array<string>;
        TargetUrl?: string;
        OutputFolder?: string;
    };
    path?: never;
    query?: never;
    url: '/umbraco/umbracocommunityhtmlexporter/api/v1/export-website';
};

export type ExportWebsiteErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ExportWebsiteResponses = {
    /**
     * OK
     */
    200: string;
};

export type ExportWebsiteResponse = ExportWebsiteResponses[keyof ExportWebsiteResponses];

export type GetDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbracocommunityhtmlexporter/api/v1/get-data';
};

export type GetDataErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetDataResponses = {
    /**
     * OK
     */
    200: DashboardViewModel;
};

export type GetDataResponse = GetDataResponses[keyof GetDataResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44396' | (string & {});
};
